backend:
  endpoints:
    info: "http://127.0.0.1:1111/log/info"
    debug: "http://127.0.0.1:1111/log/debug"
    warning: "http://127.0.0.1:1111/log/warning"
    error: "http://127.0.0.1:1111/log/error"
    critical: "http://127.0.0.1:1111/log/critical"