{
 "title": "Customer cost",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Customer costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Customer costs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "costs_total{customer=\"Vodafone\"}",
     "legendFormat": "{{customer}}"
    },
    {
     "expr": "costs_total{customer=\"Telekom\"}",
     "legendFormat": "{{customer}}"
    },
    {
     "expr": "costs_total{customer=\"1und1\"}",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Total customer cost in relation to total threshold",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "sum(costs_total)", "legendFormat": "Total cost" },
    {
     "expr": "cost_threshold{customer=\"all\"}",
     "legendFormat": "Total threshold"
    }
   ]
  },
  {
   "title": "Customer cost thresholds ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "cost_threshold{customer=\"Vodafone\"}",
     "legendFormat": "{{customer}}"
    },
    {
     "expr": "cost_threshold{customer=\"Telekom\"}",
     "legendFormat": "{{customer}}"
    },
    {
     "expr": "cost_threshold{customer=\"1und1\"}",
     "legendFormat": "{{customer}}"
    },
    {
     "expr": "cost_threshold{customer=\"all\"}",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}